@BACK_URL = https://localhost:7171/api


###
GET {{BACK_URL}}/Channels/GetAllForUser/1
Authorization: Bearer {{auth_token}}


###
GET {{BACK_URL}}/Channels/1
Authorization: Bearer {{auth_token}}


###
POST {{BACK_URL}}/Channels
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "Name": "azerty"
}


###
DELETE {{BACK_URL}}/Channels/1
Authorization: Bearer {{auth_token}}

  
  