@BACK_URL = https://localhost:7171/api


POST {{BACK_URL}}/Comments
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "content": "This is a test post comment from Comments.http",
  "postId": 2,
  "userId": 1
}


###
POST {{BACK_URL}}/Comments
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "content": "This is a test post comment from Comments.http",
  "eventId": 2,
  "userId": 1
}



###
PUT {{BACK_URL}}/Comments
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 1,
  "content": "UPDATED comment from Comments.http"
}


###
DELETE {{BACK_URL}}/Comments/2
Authorization: Bearer {{auth_token}}