@BACK_URL = https://localhost:7171/api


POST {{BACK_URL}}/Comments
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "content": "This is a test comment from Comments.http",
  "postId": 2,
  "userId": 1
}
