@BACK_URL = https://localhost:7171/api


###
# Get all events
GET {{BACK_URL}}/Event
Authorization: Bearer {{auth_token}}


###
# Get event by ID
GET {{BACK_URL}}/Event/1
Authorization: Bearer {{auth_token}}


###
# Get all events by organization
GET {{BACK_URL}}/Event/GetAllByOrganization/1
Authorization: Bearer {{auth_token}}


###
# Create event
POST {{BACK_URL}}/Event
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "EVENEMENT YNOV",
  "startDate": "2026-08-15T09:00:00Z",
  "imageUrl": "https://example.com/event-image.jpg",
  "isPublished": true,
  "organizationId": 1
}


###
# Update event
PUT {{BACK_URL}}/Event/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Tech Conference 2026 - Updated",
  "startDate": "2026-06-20T09:00:00Z",
  "imageUrl": "https://example.com/event-image-updated.jpg",
  "isPublished": true,
  "organizationId": 1
}


###
# Delete event
DELETE {{BACK_URL}}/Event/1
Authorization: Bearer {{auth_token}}


###
# Toggle interested in event (marks user as interested or removes interest)
POST {{BACK_URL}}/Event/toggle-interested/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json
