@BACK_URL = https://localhost:7171/api

POST {{BACK_URL}}/Filieres
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "Intitule": "Informatique",
  "Niveau": "M2",
  "OrganizationId": 1
}


###
GET {{BACK_URL}}/Filieres/GetAllByOrganization/1
Authorization: Bearer {{auth_token}}


###
PUT {{BACK_URL}}/Filieres
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "Id": 1,
  "Intitule": "Informatique Updated",
  "Niveau": "M2",
  "OrganizationId": 1
}


###
DELETE {{BACK_URL}}/Filieres/1
Authorization: Bearer {{auth_token}}