@BACK_URL = https://localhost:7171/api


GET {{BACK_URL}}/Organizations/1
Authorization: Bearer {{auth_token}}


###
POST {{BACK_URL}}/Organizations
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "Name": "azerty",
  "City": "Lyon",
  "PostalCode": "69200",
  "Address": "Adresse Adresse"
}


### Update Organization (Full Update)
PUT {{BACK_URL}}/Organizations
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 1,
  "Name": "Updated Organization Name",
  "City": "New City",
  "PostalCode": "75001",
  "Address": "123 Updated Street"
}