@BACK_URL = https://localhost:7171/api

POST {{BACK_URL}}/Organizations
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "Name": "azerty",
  "City": "Lyon",
  "PostalCode": "69200",
  "Address": "Adresse Adresse"
}


###
GET {{BACK_URL}}/Organizations/1
Authorization: Bearer {{auth_token}}
