@BACK_URL = https://localhost:7171/api


GET {{BACK_URL}}/Posts
Authorization: Bearer {{auth_token}}


###
GET {{BACK_URL}}/Posts/GetMostRecentWithSkip/10
Authorization: Bearer {{auth_token}}


###
GET {{BACK_URL}}/Posts/GetByUserId/4
Authorization: Bearer {{auth_token}}


###
POST {{BACK_URL}}/Posts/UploadImages
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=UploadBoundary

--UploadBoundary
Content-Disposition: form-data; name="files"; filename="image1.png"
Content-Type: image/png

< C:/Users/lukas/OneDrive/Documents/image.png
--UploadBoundary--


###
POST {{BACK_URL}}/Posts
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "content": "Post avec plusieurs images",
  "imageUrls": [
    "https://localhost:7171/uploads/posts/your-uploaded-file-1.png"
  ],
  "userId": 1
}


###
PUT {{BACK_URL}}/Posts
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 4,
  "content": "Nouveau contenu modifie",
  "imageUrls": [
    "https://cdn.example.com/posts/updated-1.png"
  ]
}


###
DELETE {{BACK_URL}}/Posts/1
Authorization: Bearer {{auth_token}}


###
# Toggle like on post (add like if not liked, remove if already liked)
POST {{BACK_URL}}/Posts/ToggleLike/2
Authorization: Bearer {{auth_token}}
Content-Type: application/json
