@BACK_URL = https://localhost:7171/api


GET {{BACK_URL}}/Posts
Authorization: Bearer {{auth_token}}



###
GET {{BACK_URL}}/Posts/GetAllByIsThread/true
Authorization: Bearer {{auth_token}}


###
POST {{BACK_URL}}/Posts
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "isThread": true,
  "Content": "QSDSDFDS de AZEZAZERE post",
  "userId": 1
}


###
DELETE {{BACK_URL}}/Posts/1
Authorization: Bearer {{auth_token}}

