// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MojiiBackend.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MojiiBackend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425150702_InitialDataAdded")]
    partial class InitialDataAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChannelUser", b =>
                {
                    b.Property<int>("ChannelsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("ChannelsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ChannelUsers", (string)null);
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.Property<int>("InterestedUsersId")
                        .HasColumnType("integer");

                    b.Property<int>("InterestingEventsId")
                        .HasColumnType("integer");

                    b.HasKey("InterestedUsersId", "InterestingEventsId");

                    b.HasIndex("InterestingEventsId");

                    b.ToTable("EventInterestedUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "STUDENT_CONCURRENCY_STAMP",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "SCHOOL_ADMIN_CONCURRENCY_STAMP",
                            Name = "SchoolAdmin",
                            NormalizedName = "SCHOOLADMIN"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "SUPER_ADMIN_CONCURRENCY_STAMP",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 101,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 102,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 103,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 104,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 105,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 106,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 107,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 108,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 109,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 110,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("NbOfLikes")
                        .HasColumnType("integer");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Content = "Super projet !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            NbOfLikes = 0,
                            PostId = 101,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 102
                        },
                        new
                        {
                            Id = 102,
                            Content = "Bravo, continue comme ça !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            NbOfLikes = 0,
                            PostId = 101,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 103
                        },
                        new
                        {
                            Id = 103,
                            Content = "J'ai les mêmes ressources, je t'envoie ça !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            NbOfLikes = 0,
                            PostId = 102,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 101
                        },
                        new
                        {
                            Id = 104,
                            Content = "Regarde la doc officielle de PyTorch.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            NbOfLikes = 0,
                            PostId = 102,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 104
                        },
                        new
                        {
                            Id = 105,
                            Content = "Moi aussi, c'était vraiment intense !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            NbOfLikes = 0,
                            PostId = 103,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 105
                        },
                        new
                        {
                            Id = 106,
                            Content = "Le prof est excellent.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            NbOfLikes = 0,
                            PostId = 103,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 106
                        },
                        new
                        {
                            Id = 107,
                            Content = "Essaie scikit-learn en premier.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            NbOfLikes = 0,
                            PostId = 104,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 107
                        },
                        new
                        {
                            Id = 108,
                            Content = "On peut travailler ensemble si tu veux.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            NbOfLikes = 0,
                            PostId = 104,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 108
                        },
                        new
                        {
                            Id = 109,
                            Content = "Je suis dispo samedi !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            NbOfLikes = 0,
                            PostId = 105,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 109
                        },
                        new
                        {
                            Id = 110,
                            Content = "Bonne idée, je suis partant.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            NbOfLikes = 0,
                            PostId = 105,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 101
                        },
                        new
                        {
                            Id = 111,
                            Content = "Hâte d'y participer !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 101,
                            NbOfLikes = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 103
                        },
                        new
                        {
                            Id = 112,
                            Content = "On forme une équipe ?",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 101,
                            NbOfLikes = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 104
                        },
                        new
                        {
                            Id = 113,
                            Content = "Très bon sujet, merci pour l'organisation.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 102,
                            NbOfLikes = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 105
                        },
                        new
                        {
                            Id = 114,
                            Content = "Est-ce qu'il y a un replay prévu ?",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 102,
                            NbOfLikes = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 106
                        },
                        new
                        {
                            Id = 115,
                            Content = "Je serai là !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 103,
                            NbOfLikes = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 107
                        },
                        new
                        {
                            Id = 116,
                            Content = "Super initiative !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 103,
                            NbOfLikes = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 108
                        },
                        new
                        {
                            Id = 117,
                            Content = "Workshop très utile pour les projets.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 104,
                            NbOfLikes = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 109
                        },
                        new
                        {
                            Id = 118,
                            Content = "Quelle version de Docker sera utilisée ?",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 104,
                            NbOfLikes = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 102
                        },
                        new
                        {
                            Id = 119,
                            Content = "Des entreprises tech seront présentes ?",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 105,
                            NbOfLikes = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 103
                        },
                        new
                        {
                            Id = 120,
                            Content = "J'ai envoyé mon CV à 3 entreprises !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 105,
                            NbOfLikes = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 104
                        });
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("DateLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DayLabel")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("DefaultInterestedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("MonthLabel")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Address = "24 Rue Pasteur, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Lundi 15 Mars 2027 - 09h00",
                            DayLabel = "15",
                            DefaultInterestedCount = 0,
                            Description = "Hackathon annuel Ynov Lyon",
                            IsPublished = true,
                            Location = "Ynov Lyon",
                            MonthLabel = "MARS",
                            Name = "Hackathon Ynov 2025",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 3, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 102,
                            Address = "24 Rue Pasteur, Bâtiment A, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Samedi 10 Avril 2027 - 14h00",
                            DayLabel = "10",
                            DefaultInterestedCount = 0,
                            Description = "Conférence sur l'IA et ses enjeux éthiques",
                            IsPublished = true,
                            Location = "Amphi A",
                            MonthLabel = "AVR",
                            Name = "Conférence IA & Éthique",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 4, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 103,
                            Address = "24 Rue Pasteur, Espace Coworking, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Jeudi 20 Mai 2027 - 18h00",
                            DayLabel = "20",
                            DefaultInterestedCount = 0,
                            Description = "Soirée networking pour les développeurs",
                            IsPublished = true,
                            Location = "Espace Collaboratif",
                            MonthLabel = "MAI",
                            Name = "Soirée Networking Dev",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 5, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 104,
                            Address = "24 Rue Pasteur, Salle 3.12, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Samedi 5 Juin 2027 - 10h00",
                            DayLabel = "5",
                            DefaultInterestedCount = 0,
                            Description = "Workshop pratique Docker et intégration continue",
                            IsPublished = false,
                            Location = "Salle Informatique 3",
                            MonthLabel = "JUIN",
                            Name = "Workshop Docker & CI/CD",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 6, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 105,
                            Address = "24 Rue Pasteur, Hall principal, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Vendredi 25 Juin 2027 - 09h00",
                            DayLabel = "25",
                            DefaultInterestedCount = 0,
                            Description = "Forum annuel de recrutement",
                            IsPublished = true,
                            Location = "Hall Principal",
                            MonthLabel = "JUIN",
                            Name = "Forum des entreprises",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 6, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 106,
                            Address = "24 Rue Pasteur, Pôle Carrières, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Dimanche 12 Septembre 2027 - 13h30",
                            DayLabel = "12",
                            DefaultInterestedCount = 0,
                            Description = "Atelier pratique pour optimiser CV et LinkedIn",
                            IsPublished = true,
                            Location = "Salle Carrières",
                            MonthLabel = "SEPT",
                            Name = "Atelier CV & LinkedIn",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 9, 12, 13, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 107,
                            Address = "24 Rue Pasteur, Campus Ynov Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Dimanche 3 Octobre 2027 - 17h30",
                            DayLabel = "3",
                            DefaultInterestedCount = 0,
                            Description = "Découverte des filières tech et des projets",
                            IsPublished = true,
                            Location = "Campus Ynov",
                            MonthLabel = "OCT",
                            Name = "Journée Portes Ouvertes Tech",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 10, 3, 17, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 108,
                            Address = "10 Rue de la République, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 110,
                            DateLabel = "Samedi 10 Juillet 2027 - 09h00",
                            DayLabel = "10",
                            DefaultInterestedCount = 0,
                            Description = "Capture The Flag cybersécurité",
                            IsPublished = true,
                            Location = "ESGI Lyon",
                            MonthLabel = "JUIL",
                            Name = "CTF Cybersécurité ESGI",
                            OrganizationId = 102,
                            StartDate = new DateTime(2027, 7, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 109,
                            Address = "24 Rue Pasteur, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Jeudi 15 Avril 2027 - 09h00",
                            DayLabel = "15",
                            DefaultInterestedCount = 0,
                            Description = "Échanges sur les nouveautés Flutter.",
                            IsPublished = true,
                            Location = "Labo Mobile",
                            MonthLabel = "AVR",
                            Name = "Meetup Flutter & Dart",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 4, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 110,
                            Address = "24 Rue Pasteur, Bâtiment B, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Lundi 10 Mai 2027 - 14h00",
                            DayLabel = "10",
                            DefaultInterestedCount = 0,
                            Description = "Concevoir des interfaces centrées utilisateur.",
                            IsPublished = true,
                            Location = "Studio Créa",
                            MonthLabel = "MAI",
                            Name = "Masterclass UI/UX Design",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 5, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 111,
                            Address = "24 Rue Pasteur, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Dimanche 20 Juin 2027 - 18h00",
                            DayLabel = "20",
                            DefaultInterestedCount = 0,
                            Description = "Compétition de jeux vidéo inter-spécialités.",
                            IsPublished = true,
                            Location = "Foyer Étudiant",
                            MonthLabel = "JUIN",
                            Name = "Tournoi E-sport Inter-Filière",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 6, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 112,
                            Address = "24 Rue Pasteur, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Lundi 5 Juillet 2027 - 10h00",
                            DayLabel = "5",
                            DefaultInterestedCount = 0,
                            Description = "Semaine intensive pour booster vos compétences.",
                            IsPublished = true,
                            Location = "Espace Coworking",
                            MonthLabel = "JUIL",
                            Name = "Summer Coding Camp",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 7, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 113,
                            Address = "24 Rue Pasteur, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Dimanche 25 Juillet 2027 - 09h00",
                            DayLabel = "25",
                            DefaultInterestedCount = 0,
                            Description = "Moment convivial avant les vacances d'été.",
                            IsPublished = true,
                            Location = "Toit-Terrasse",
                            MonthLabel = "JUIL",
                            Name = "Barbecue de fin d'année",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 7, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 114,
                            Address = "24 Rue Pasteur, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Mardi 12 Octobre 2027 - 13h30",
                            DayLabel = "12",
                            DefaultInterestedCount = 0,
                            Description = "Conférences sur les nouvelles menaces web.",
                            IsPublished = true,
                            Location = "Amphi Principal",
                            MonthLabel = "OCT",
                            Name = "Séminaire Cybersécurité",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 10, 12, 13, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 115,
                            Address = "Cité Internationale, Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = 101,
                            DateLabel = "Mercredi 3 Novembre 2027 - 17h30",
                            DayLabel = "3",
                            DefaultInterestedCount = 0,
                            Description = "Cérémonie officielle et soirée de prestige.",
                            IsPublished = true,
                            Location = "Palais des Congrès",
                            MonthLabel = "NOV",
                            Name = "Gala de Remise des Diplômes",
                            OrganizationId = 101,
                            StartDate = new DateTime(2027, 11, 3, 17, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Filiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Filieres");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Intitule = "Développement Web",
                            Niveau = "M2",
                            OrganizationId = 101,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Intitule = "Intelligence Artificielle",
                            Niveau = "M1",
                            OrganizationId = 101,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Intitule = "Cybersécurité",
                            Niveau = "M2",
                            OrganizationId = 102,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserSenderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Content = "Le Hackathon Ynov 2025 a été publié !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Type = "NewEventCreated",
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 101
                        },
                        new
                        {
                            Id = 102,
                            Content = "Quelqu'un a commenté votre post.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Type = "NewCommentOnPost",
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 102
                        },
                        new
                        {
                            Id = 103,
                            Content = "Votre post a reçu un like.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Type = "NewLikeOnPost",
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 103
                        },
                        new
                        {
                            Id = 104,
                            Content = "Un nouvel événement est disponible.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Type = "NewEventCreated",
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 104
                        },
                        new
                        {
                            Id = 105,
                            Content = "Votre compte a été activé.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Type = "AccountActivated",
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 105
                        },
                        new
                        {
                            Id = 106,
                            Content = "Vous avez reçu un nouveau message.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Type = "NewMessage",
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 106
                        },
                        new
                        {
                            Id = 107,
                            Content = "L'événement Workshop Docker a été mis à jour.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Type = "EventUpdated",
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 107
                        },
                        new
                        {
                            Id = 108,
                            Content = "Un de vos posts a été signalé.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Type = "PostReported",
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 108
                        },
                        new
                        {
                            Id = 109,
                            Content = "Votre post a reçu un like.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Type = "NewLikeOnPost",
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 109
                        },
                        new
                        {
                            Id = 110,
                            Content = "Le CTF Cybersécurité ESGI est publié !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Type = "NewEventCreated",
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 110
                        });
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Address = "24 Rue Pasteur, Lyon",
                            City = "Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ynov Lyon",
                            PostalCode = "75001",
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 102,
                            Address = "10 Rue de la République, Lyon",
                            City = "Lyon",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Name = "ESGI Lyon",
                            PostalCode = "69001",
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("NbOfLikes")
                        .HasColumnType("integer");

                    b.Property<int>("NbOfReports")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Content = "Voici mon premier projet React en B3 Dev Web !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrls = new string[0],
                            NbOfLikes = 0,
                            NbOfReports = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 101
                        },
                        new
                        {
                            Id = 102,
                            Content = "Quelqu'un a des ressources pour apprendre PyTorch ?",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrls = new string[0],
                            NbOfLikes = 0,
                            NbOfReports = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 102
                        },
                        new
                        {
                            Id = 103,
                            Content = "Le cours d'algorithmique était intense aujourd'hui.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrls = new string[0],
                            NbOfLikes = 0,
                            NbOfReports = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 103
                        },
                        new
                        {
                            Id = 104,
                            Content = "Tips pour le projet de machine learning ?",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrls = new string[0],
                            NbOfLikes = 0,
                            NbOfReports = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 104
                        },
                        new
                        {
                            Id = 105,
                            Content = "Qui veut faire du co-working ce weekend ?",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrls = new string[0],
                            NbOfLikes = 0,
                            NbOfReports = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 105
                        },
                        new
                        {
                            Id = 106,
                            Content = "Je viens de finir mon stage, c'était incroyable !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrls = new string[0],
                            NbOfLikes = 0,
                            NbOfReports = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 106
                        },
                        new
                        {
                            Id = 107,
                            Content = "Des nouvelles du Hackathon Ynov Lyon ?",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrls = new string[0],
                            NbOfLikes = 0,
                            NbOfReports = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 107
                        },
                        new
                        {
                            Id = 108,
                            Content = "Retour d'expérience sur Docker et Kubernetes.",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrls = new string[0],
                            NbOfLikes = 0,
                            NbOfReports = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 108
                        },
                        new
                        {
                            Id = 109,
                            Content = "Bonne chance à tous pour les partiels !",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrls = new string[0],
                            NbOfLikes = 0,
                            NbOfReports = 0,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 109
                        });
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Token" }, "IX_RefreshToken_Token")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "IX_RefreshToken_UserId_CreatedAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ReporterUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TargetCommentId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetPostId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("TargetCommentId");

                    b.HasIndex("TargetPostId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Comment = "Comportement inapproprié",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Harassment",
                            ReporterUserId = 101,
                            Status = "Open",
                            TargetUserId = 103,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 102,
                            Comment = "Envoi de messages répétitifs",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Spam",
                            ReporterUserId = 102,
                            Status = "Reviewed",
                            TargetUserId = 104,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "InapropriateContent",
                            ReporterUserId = 103,
                            Status = "Open",
                            TargetPostId = 102,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "FakeInformation",
                            ReporterUserId = 104,
                            Status = "Closed",
                            TargetPostId = 105,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "HateSpeech",
                            ReporterUserId = 105,
                            Status = "Open",
                            TargetCommentId = 101,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Biography")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("FiliereId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastConnectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePicUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FiliereId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OrganizationId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP1",
                            Email = "anis.benjemia@ynov.com",
                            EmailConfirmed = true,
                            FiliereId = 101,
                            FirstName = "Anis",
                            IsConnected = false,
                            LastName = "Ben Jemia",
                            LockoutEnabled = false,
                            NormalizedEmail = "ANIS.BENJEMIA@YNOV.COM",
                            NormalizedUserName = "ANIS.BENJEMIA",
                            OrganizationId = 101,
                            PasswordHash = "AQAAAAIAAYagAAAAEJMYvnVYX5xc6g1z+x87i4aLP/O2sLWIgp31WRqewgUw2vGfKTOApvSzWBnLzc58Ag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SECSTAMP1",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "anis.benjemia"
                        },
                        new
                        {
                            Id = 102,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP2",
                            Email = "lukas.bouhlel@ynov.com",
                            EmailConfirmed = true,
                            FiliereId = 102,
                            FirstName = "Lukas",
                            IsConnected = false,
                            LastName = "Bouhlel",
                            LockoutEnabled = false,
                            NormalizedEmail = "LUKAS.BOUHLEL@YNOV.COM",
                            NormalizedUserName = "LUKAS.BOUHLEL",
                            OrganizationId = 101,
                            PasswordHash = "AQAAAAIAAYagAAAAEJMYvnVYX5xc6g1z+x87i4aLP/O2sLWIgp31WRqewgUw2vGfKTOApvSzWBnLzc58Ag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SECSTAMP2",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "lukas.bouhlel"
                        },
                        new
                        {
                            Id = 103,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP3",
                            Email = "elias.eloudghiri@ynov.com",
                            EmailConfirmed = true,
                            FiliereId = 101,
                            FirstName = "Elias",
                            IsConnected = false,
                            LastName = "El Oudghiri",
                            LockoutEnabled = false,
                            NormalizedEmail = "ELIAS.ELOUDGHIRI@YNOV.COM",
                            NormalizedUserName = "ELIAS.ELOUDGHIRI",
                            OrganizationId = 101,
                            PasswordHash = "AQAAAAIAAYagAAAAEJMYvnVYX5xc6g1z+x87i4aLP/O2sLWIgp31WRqewgUw2vGfKTOApvSzWBnLzc58Ag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SECSTAMP3",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "elias.eloudghiri"
                        },
                        new
                        {
                            Id = 104,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP4",
                            Email = "matthieu.vernier@ynov.com",
                            EmailConfirmed = true,
                            FiliereId = 102,
                            FirstName = "Matthieu",
                            IsConnected = false,
                            LastName = "Vernier",
                            LockoutEnabled = false,
                            NormalizedEmail = "MATTHIEU.VERNIER@YNOV.COM",
                            NormalizedUserName = "MATTHIEU.VERNIER",
                            OrganizationId = 101,
                            PasswordHash = "AQAAAAIAAYagAAAAEJMYvnVYX5xc6g1z+x87i4aLP/O2sLWIgp31WRqewgUw2vGfKTOApvSzWBnLzc58Ag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SECSTAMP4",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "matthieu.vernier"
                        },
                        new
                        {
                            Id = 105,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP5",
                            Email = "hajar.zahoui@ynov.com",
                            EmailConfirmed = true,
                            FiliereId = 101,
                            FirstName = "Hajar",
                            IsConnected = false,
                            LastName = "Zahoui",
                            LockoutEnabled = false,
                            NormalizedEmail = "HAJAR.ZAHOUI@YNOV.COM",
                            NormalizedUserName = "HAJAR.ZAHOUI",
                            OrganizationId = 101,
                            PasswordHash = "AQAAAAIAAYagAAAAEJMYvnVYX5xc6g1z+x87i4aLP/O2sLWIgp31WRqewgUw2vGfKTOApvSzWBnLzc58Ag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SECSTAMP5",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "hajar.zahoui"
                        },
                        new
                        {
                            Id = 106,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP6",
                            Email = "khadidja.khababa@ynov.com",
                            EmailConfirmed = false,
                            FiliereId = 102,
                            FirstName = "Khadidja",
                            IsConnected = false,
                            LastName = "Khababa",
                            LockoutEnabled = false,
                            NormalizedEmail = "KHADIDJA.KHABABA@YNOV.COM",
                            NormalizedUserName = "KHADIDJA.KHABABA",
                            OrganizationId = 101,
                            PhoneNumberConfirmed = false,
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "khadidja.khababa"
                        },
                        new
                        {
                            Id = 107,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP7",
                            Email = "lea.regoudis@ynov.com",
                            EmailConfirmed = true,
                            FiliereId = 101,
                            FirstName = "Léa",
                            IsConnected = false,
                            LastName = "Regoudis",
                            LockoutEnabled = false,
                            NormalizedEmail = "LEA.REGOUDIS@YNOV.COM",
                            NormalizedUserName = "LEA.REGOUDIS",
                            OrganizationId = 101,
                            PasswordHash = "AQAAAAIAAYagAAAAEJMYvnVYX5xc6g1z+x87i4aLP/O2sLWIgp31WRqewgUw2vGfKTOApvSzWBnLzc58Ag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SECSTAMP7",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "lea.regoudis"
                        },
                        new
                        {
                            Id = 108,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP8",
                            Email = "hugo.laurent@ynov.com",
                            EmailConfirmed = true,
                            FiliereId = 102,
                            FirstName = "Hugo",
                            IsConnected = false,
                            LastName = "Laurent",
                            LockoutEnabled = false,
                            NormalizedEmail = "HUGO.LAURENT@YNOV.COM",
                            NormalizedUserName = "HUGO.LAURENT",
                            OrganizationId = 101,
                            PasswordHash = "AQAAAAIAAYagAAAAEJMYvnVYX5xc6g1z+x87i4aLP/O2sLWIgp31WRqewgUw2vGfKTOApvSzWBnLzc58Ag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SECSTAMP8",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "hugo.laurent"
                        },
                        new
                        {
                            Id = 109,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP9",
                            Email = "ines.thomas@ynov.com",
                            EmailConfirmed = true,
                            FiliereId = 101,
                            FirstName = "Ines",
                            IsConnected = false,
                            LastName = "Thomas",
                            LockoutEnabled = false,
                            NormalizedEmail = "INES.THOMAS@YNOV.COM",
                            NormalizedUserName = "INES.THOMAS",
                            OrganizationId = 101,
                            PasswordHash = "AQAAAAIAAYagAAAAEJMYvnVYX5xc6g1z+x87i4aLP/O2sLWIgp31WRqewgUw2vGfKTOApvSzWBnLzc58Ag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SECSTAMP9",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "ines.thomas"
                        },
                        new
                        {
                            Id = 110,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP10",
                            Email = "jules.garnier@esgi.fr",
                            EmailConfirmed = true,
                            FiliereId = 103,
                            FirstName = "Jules",
                            IsConnected = false,
                            LastName = "Garnier",
                            LockoutEnabled = false,
                            NormalizedEmail = "JULES.GARNIER@ESGI.FR",
                            NormalizedUserName = "JULES.GARNIER",
                            OrganizationId = 102,
                            PasswordHash = "AQAAAAIAAYagAAAAEJMYvnVYX5xc6g1z+x87i4aLP/O2sLWIgp31WRqewgUw2vGfKTOApvSzWBnLzc58Ag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SECSTAMP10",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "jules.garnier"
                        });
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.UserState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InitiatorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("StateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TargetedUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorUserId");

                    b.HasIndex("TargetedUserId");

                    b.ToTable("UserStates");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            InitiatorUserId = 101,
                            StateType = "Blocked",
                            TargetedUserId = 103,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            InitiatorUserId = 102,
                            StateType = "Muted",
                            TargetedUserId = 104,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            InitiatorUserId = 103,
                            StateType = "Blocked",
                            TargetedUserId = 105,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            InitiatorUserId = 104,
                            StateType = "Muted",
                            TargetedUserId = 106,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            InitiatorUserId = 105,
                            StateType = "Blocked",
                            TargetedUserId = 107,
                            UpdatedAt = new DateTime(2026, 4, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PostUser", b =>
                {
                    b.Property<int>("HavingLikedUsersId")
                        .HasColumnType("integer");

                    b.Property<int>("LikedPostsId")
                        .HasColumnType("integer");

                    b.HasKey("HavingLikedUsersId", "LikedPostsId");

                    b.HasIndex("LikedPostsId");

                    b.ToTable("PostLikes", (string)null);
                });

            modelBuilder.Entity("ChannelUser", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MojiiBackend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InterestedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MojiiBackend.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("InterestingEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MojiiBackend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Comment", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("MojiiBackend.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MojiiBackend.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Event", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MojiiBackend.Domain.Entities.Organization", "Organization")
                        .WithMany("Events")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Filiere", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.Organization", "Organization")
                        .WithMany("Filieres")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Message", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MojiiBackend.Domain.Entities.User", "UserSender")
                        .WithMany("Messages")
                        .HasForeignKey("UserSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Post", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.User", "User")
                        .WithMany("CreatedPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Report", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.User", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MojiiBackend.Domain.Entities.Comment", "TargetComment")
                        .WithMany()
                        .HasForeignKey("TargetCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MojiiBackend.Domain.Entities.Post", "TargetPost")
                        .WithMany()
                        .HasForeignKey("TargetPostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MojiiBackend.Domain.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ReporterUser");

                    b.Navigation("TargetComment");

                    b.Navigation("TargetPost");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.User", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.Filiere", "Filiere")
                        .WithMany("Users")
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MojiiBackend.Domain.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiere");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.UserState", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.User", "InitiatorUser")
                        .WithMany("UserStates")
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MojiiBackend.Domain.Entities.User", "TargetedUser")
                        .WithMany()
                        .HasForeignKey("TargetedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InitiatorUser");

                    b.Navigation("TargetedUser");
                });

            modelBuilder.Entity("PostUser", b =>
                {
                    b.HasOne("MojiiBackend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("HavingLikedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MojiiBackend.Domain.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("LikedPostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Channel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Filiere", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Filieres");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("MojiiBackend.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CreatedPosts");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserStates");
                });
#pragma warning restore 612, 618
        }
    }
}
